name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write     # Allows pushing changes to the repository
  pages: write        # Allows deployment to GitHub Pages
  id-token: write     # Allows the workflow to use ID tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Set up Git Authentication using GITHUB_TOKEN
      #   run: |
      #     git config --global user.name "GitHub Action"
      #     git config --global user.email "action@github.com"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Santhosh-Sathyamurthy/Santhosh-Sathyamurthy.github.io.git

      # - name: Get last commit date
      #   id: get_last_commit_date
      #   run: |
      #     LAST_MODIFIED=$(git log -1 --format=%cd --date=format:"%I:%M %p %d-%m-%Y")
      #     echo "LAST_MODIFIED=$LAST_MODIFIED" >> $GITHUB_ENV

      # - name: Update last modified date in index.html
      #   run: |
      #     sed -i 's|<span id="lastModified">.*</span>|<span id="lastModified">'"$LAST_MODIFIED"'</span>|g' ./index.html

      - name: Commit and Push Changes
        run: |
          git add index.html
          git commit -m "Update last modified date to $LAST_MODIFIED"
          git push origin main

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./ 
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
