name: Page Build Deployment

on:
  workflow_run:
    workflows: ["Update Last Modified"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Your build and deployment commands here
          echo "Building and deploying the site..."
