name: Update Last Modified Date

on:
  push:
    branches:
      - main  # Change if your default branch is something else

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git authentication using PAT
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Santhosh-Sathyamurthy/Santhosh-Sathyamurthy.github.io.git

    - name: Get last commit date
      id: get_last_commit_date
      run: |
        LAST_MODIFIED=$(git log -1 --format=%cd --date=format:"%H:%M %d-%m-%Y")
        echo "LAST_MODIFIED=$LAST_MODIFIED" >> $GITHUB_ENV

    - name: Replace placeholder with last commit date
      run: |
        sed -i 's/LAST_MODIFIED_PLACEHOLDER/'"$LAST_MODIFIED"'/g' ./index.html

    - name: Commit and push changes
      run: |
        git add index.html
        git commit -m "Update last modified date to $LAST_MODIFIED"
        git push origin main
